name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.9']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Install dependencies (quiet)
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()' > /dev/null 2>&1

      - name: Run tests (quiet unless failed)
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.test(; verbose=false)
          ' > test_output.log 2>&1 || (cat test_output.log && exit 1)
